const data = [
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    },
    {
        name:"Tushar",
        github:"tush-tr"
    }
]
module.exports = data;